data:
  dataset: "amazon_books"
  batch_size: 512
  normalize_data: False
  embedding_dimension: "meta"

model:
  hidden_dimensions: [512, 256]
  latent_dimension: 64
  num_codebook_layers: 3
  codebook_clusters: 256
  commitment_weight: 0.25

train:
  learning_rate: 0.001
  weight_decay: 0.0
  num_epochs: 256
  warmup_epochs: 25
  validation_step: 10

general:
  seed: 2026
  use_wandb: True
  wandb_project: "semantic_id_amazon_books"
  wandb_entity: "justin-hangoebl-master-thesis"
  save_model: True
